### PR TITLE
Include tests to the release tarball

### LINKED ISSUE #54: Add tests to release tarball
Same background as #53. Tests are desirable for QA / CI purposes on the packaging side.

### PR DESCRIPTION
**Pull request by ghisvail**
Closes #54

### CODE REVIEW

**Comment by mpastell** [comment]
The tests are currently quite specific wrt some libraries (pygments). Is that a problem for packaging? I'll merge this now, sorry for the delay.

**Comment by rlaverde** [comment]
Maybe using an `extra_requires` in `setup.py`, then for testing you could use `pip install pweave[test]` and It'll install test dependencies. I could provide a PR with that change

**Comment by ghisvail** [comment]
Having `extras_require = {'test': = [...]`} in the setup metadata would make the test requirements more explicit, indeed.

**Comment by mpastell** [comment]
@rlaverde That would be great!

**Pull request merged**
